esp_joystick_node:
  ros__parameters:
    # Serial communication settings
    serial_port: "/dev/ttyUSB0" # Change to match your system (e.g., /dev/ttyACM0, /dev/ttyUSB1)
    baud_rate: 115200
    crc_validation_enabled: true
    reconnect_interval_ms: 2000 # ms
